name: 'OpenAPI Coverage'
description: 'Checks how many API routes are covered at the OpenAPI spec'
branding:
  icon: 'check-circle'
  color: 'orange'
inputs:
  path:
    description: 'Base path for the application'
    required: true
    default: '.'
  language:
    description: 'Main language for your application'
    required: true
  ignore-routes:
    description: 'Filter routes that match these regular expressions (one per line)'
    required: false
  ignore-routes-file:
    description: 'Filter routes that match the regular expressions from this file (one per line)'
    required: false
  spec:
    description: 'Filepath for the OpenAPI spec'
    required: false
  debug:
    description: 'Whether to enable verbose output'
    required: false
    default: 'false'
outputs:
  routes_discovered:
    description: 'How many application routes were discovered'
  endpoints_in_spec:
    description: 'How many endpoints were found at the OpenAPI spec'
  coverage_percentage:
    description: 'Coverage in percentage'
runs:
  using: 'node20'
  main: 'dist/entrypoints/github-actions.js'
