#!/usr/bin/env php
<?php

use OpenApiCoverage\Command\Command;
use OpenApiCoverage\Command\CommandEntrypoint;

require __DIR__ . '/vendor/autoload.php';

try {
    $options = \getopt('', [
        'filter-routes:',
        'spec:',
        'debug',
    ], $restIndex);

    // Application path
    $posArgs = array_slice($argv, $restIndex);
    $basePath = $posArgs[0] ?? getcwd();

    // Ignore routes that match these regular expressions
    $options['filter-routes'] = (empty($options['filter-routes']))
        ? null
        : array_map('trim', explode(',', $options['filter-routes']));

    $entrypoint = new CommandEntrypoint(
        $basePath,
        $options['debug'] ?? false,
        $options['filter-routes'],
        $options['spec'] ?? null
    );

    $command = new Command($entrypoint);
    $response = $command->run();

    echo json_encode($response, JSON_PRETTY_PRINT);
} catch (InvalidArgumentException $e) {
    fwrite(
        STDERR,
        "Error: {$e->getMessage()}" . PHP_EOL .
        "Usage: {$argv[0]} [options] [application-path]" . PHP_EOL .
        PHP_EOL .
        'Options:' . PHP_EOL .
        '  --filter <arquivo>   Informa um arquivo que retorna uma função responsável' . PHP_EOL .
        '                       por filtrar se uma rota deve ser considerada ou não' . PHP_EOL .
        '  --openapi <arquivo>  Arquivo YAML da especificação da OpenAPI. Se não passado,' . PHP_EOL .
        '                       tentaremos encontrar um arquivo openapi.yaml na aplicação' . PHP_EOL .
        '  --debug              Prints debugging information' . PHP_EOL
    );
    $code = $e->getCode();
    die(($code > 0) ? $code : 1);
} catch (Throwable $e) {
    fwrite(
        STDERR,
        "Error: {$e->getMessage()}"
    );
    $code = $e->getCode();
    die(($code > 0) ? $code : 1);
}
