name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Installing dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/'
          message: ':package: Compiling'
          default_author: github_actor
